# Generated by Django 3.1.4 on 2023-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parentId', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
