# Generated by Django 3.1.4 on 2023-11-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='subAgents',
            field=models.ManyToManyField(blank=True, to='agents.Agent'),
        ),
    ]
